/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuksesRouteImport } from './routes/sukses'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminKonsultasiRouteImport } from './routes/admin/konsultasi'
import { Route as AdminPertanyaanRouteImport } from './routes/admin/pertanyaan'
import { Route as AdminPengaturanRouteImport } from './routes/admin/pengaturan'
import { Route as AdminTestingRouteImport } from './routes/admin/testing'
import { Route as AdminPromptRouteImport } from './routes/admin/prompt'
import { Route as FormulirJenjangRouteImport } from './routes/formulir.$jenjang'

const SuksesRoute = SuksesRouteImport.update({
  id: '/sukses',
  path: '/sukses',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulirJenjangRoute = FormulirJenjangRouteImport.update({
  id: '/formulir/$jenjang',
  path: '/formulir/$jenjang',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKonsultasiRoute = AdminKonsultasiRouteImport.update({
  id: '/konsultasi',
  path: '/konsultasi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPertanyaanRoute = AdminPertanyaanRouteImport.update({
  id: '/pertanyaan',
  path: '/pertanyaan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPengaturanRoute = AdminPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestingRoute = AdminTestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromptRoute = AdminPromptRouteImport.update({
  id: '/prompt',
  path: '/prompt',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sukses': typeof SuksesRoute
  '/login': typeof LoginRoute
  '/formulir/$jenjang': typeof FormulirJenjangRoute
  '/admin': typeof AdminRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/konsultasi': typeof AdminKonsultasiRoute
  '/admin/pertanyaan': typeof AdminPertanyaanRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/testing': typeof AdminTestingRoute
  '/admin/prompt': typeof AdminPromptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sukses': typeof SuksesRoute
  '/login': typeof LoginRoute
  '/formulir/$jenjang': typeof FormulirJenjangRoute
  '/admin': typeof AdminIndexRoute
  '/admin/konsultasi': typeof AdminKonsultasiRoute
  '/admin/pertanyaan': typeof AdminPertanyaanRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/testing': typeof AdminTestingRoute
  '/admin/prompt': typeof AdminPromptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sukses': typeof SuksesRoute
  '/login': typeof LoginRoute
  '/formulir/$jenjang': typeof FormulirJenjangRoute
  '/admin': typeof AdminRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/konsultasi': typeof AdminKonsultasiRoute
  '/admin/pertanyaan': typeof AdminPertanyaanRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/testing': typeof AdminTestingRoute
  '/admin/prompt': typeof AdminPromptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sukses' | '/login' | '/formulir/$jenjang' | '/admin' | '/admin/' | '/admin/konsultasi' | '/admin/pertanyaan' | '/admin/pengaturan' | '/admin/testing' | '/admin/prompt'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sukses' | '/login' | '/formulir/$jenjang' | '/admin' | '/admin/konsultasi' | '/admin/pertanyaan' | '/admin/pengaturan' | '/admin/testing' | '/admin/prompt'
  id: '__root__' | '/' | '/sukses' | '/login' | '/formulir/$jenjang' | '/admin' | '/admin/' | '/admin/konsultasi' | '/admin/pertanyaan' | '/admin/pengaturan' | '/admin/testing' | '/admin/prompt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SuksesRoute: typeof SuksesRoute
  LoginRoute: typeof LoginRoute
  FormulirJenjangRoute: typeof FormulirJenjangRoute
  AdminRoute: typeof AdminRoute
}

const AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminKonsultasiRoute: AdminKonsultasiRoute,
  AdminPertanyaanRoute: AdminPertanyaanRoute,
  AdminPengaturanRoute: AdminPengaturanRoute,
  AdminTestingRoute: AdminTestingRoute,
  AdminPromptRoute: AdminPromptRoute,
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sukses': {
      id: '/sukses'
      path: '/sukses'
      fullPath: '/sukses'
      preLoaderRoute: typeof SuksesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulir/$jenjang': {
      id: '/formulir/$jenjang'
      path: '/formulir/$jenjang'
      fullPath: '/formulir/$jenjang'
      preLoaderRoute: typeof FormulirJenjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/konsultasi': {
      id: '/admin/konsultasi'
      path: '/konsultasi'
      fullPath: '/admin/konsultasi'
      preLoaderRoute: typeof AdminKonsultasiRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/pertanyaan': {
      id: '/admin/pertanyaan'
      path: '/pertanyaan'
      fullPath: '/admin/pertanyaan'
      preLoaderRoute: typeof AdminPertanyaanRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/pengaturan': {
      id: '/admin/pengaturan'
      path: '/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AdminPengaturanRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/testing': {
      id: '/admin/testing'
      path: '/testing'
      fullPath: '/admin/testing'
      preLoaderRoute: typeof AdminTestingRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/prompt': {
      id: '/admin/prompt'
      path: '/prompt'
      fullPath: '/admin/prompt'
      preLoaderRoute: typeof AdminPromptRouteImport
      parentRoute: typeof AdminRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SuksesRoute: SuksesRoute,
  LoginRoute: LoginRoute,
  FormulirJenjangRoute: FormulirJenjangRoute,
  AdminRoute: AdminRoute._addFileChildren(AdminRouteChildren),
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
