/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuksesRouteImport } from './routes/sukses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormulirJenjangRouteImport } from './routes/formulir.$jenjang'

const SuksesRoute = SuksesRouteImport.update({
  id: '/sukses',
  path: '/sukses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulirJenjangRoute = FormulirJenjangRouteImport.update({
  id: '/formulir/$jenjang',
  path: '/formulir/$jenjang',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sukses': typeof SuksesRoute
  '/formulir/$jenjang': typeof FormulirJenjangRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sukses': typeof SuksesRoute
  '/formulir/$jenjang': typeof FormulirJenjangRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sukses': typeof SuksesRoute
  '/formulir/$jenjang': typeof FormulirJenjangRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sukses' | '/formulir/$jenjang'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sukses' | '/formulir/$jenjang'
  id: '__root__' | '/' | '/sukses' | '/formulir/$jenjang'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SuksesRoute: typeof SuksesRoute
  FormulirJenjangRoute: typeof FormulirJenjangRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sukses': {
      id: '/sukses'
      path: '/sukses'
      fullPath: '/sukses'
      preLoaderRoute: typeof SuksesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulir/$jenjang': {
      id: '/formulir/$jenjang'
      path: '/formulir/$jenjang'
      fullPath: '/formulir/$jenjang'
      preLoaderRoute: typeof FormulirJenjangRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SuksesRoute: SuksesRoute,
  FormulirJenjangRoute: FormulirJenjangRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
